### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by maliming** [MannRobertJ/ScopedDependencyIssue#1]
`ScopedDependencyIssue/test/ScopedDependencyIssue.EntityFrameworkCore.Tests/EntityFrameworkCore/ScopedDependencyIssueEntityFrameworkCoreTestModule.cs(69,34): error CS7036: There is no argument given that corresponds to the required parameter 'serviceScopeFactory' of 'ScopedDependencyIssueDbContext.ScopedDependencyIssueDbContext(DbContextOptions<ScopedDependencyIssueDbContext>, IServiceScopeFactory)' `

**Comment by MannRobertJ** [comment]
Fixed
